app/controllers/auth_controller.py
from flask import Blueprint, request, redirect, render_template, url_for, flash, session
from ..models import Usuario, Rol
from flask_login import login_user, logout_user, login_required, current_user
from app import db
import re

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")

def is_password_strong(password):
    """Verifica si la contraseña es fuerte usando expresiones regulares."""
    strong_password_regex = re.compile(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?\":{}|<>]).{8,}$")
    return strong_password_regex.match(password) is not None

@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        
        # Obtener el número de intentos fallidos o establecerlo en 0 si no existe
        failed_attempts = session.get('failed_attempts', 0)

        user = Usuario.query.filter_by(username=username).first()
        if user and user.check_password(password) and failed_attempts < 5:
            login_user(user)
            session['failed_attempts'] = 0  # Reset the failed login attempt counter
            return redirect(url_for("main.home"))
        
        # Incrementar los intentos fallidos si la autenticación falla
        failed_attempts += 1
        session['failed_attempts'] = failed_attempts

        if failed_attempts >= 5:
            flash("Has alcanzado el número máximo de intentos. Inténtalo más tarde.", "error")
        else:
            flash("Nombre de usuario o contraseña incorrecta", "error")
        
    return render_template("auth/login.html", failed_attempts=session.get('failed_attempts', 0))


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username")
        password = request.form.get("password")
        role_id = request.form.get("role")

        # Validación de disponibilidad de email y username y fortaleza de contraseña
        if Usuario.is_username_taken(username):
            flash("El nombre de usuario ya está registrado.", "error")
        elif Usuario.is_email_taken(email):
            flash("El email ya está registrado.", "error")
        elif not is_password_strong(password):
            flash("La contraseña no cumple con los requisitos de seguridad.", "error")
        else:
            # Validación de rol y creación de usuario
            role = Rol.query.get(role_id)
            if not role:
                flash("Rol seleccionado no es válido", "error")
            else:
                user = Usuario(email=email, username=username, rol_id=role.id)
                user.set_password(password)  # Asegurar que la contraseña se hashee
                try:
                    db.session.add(user)
                    db.session.commit()
                    flash("Registro exitoso. Ahora puedes iniciar sesión.", "success")
                    return redirect(url_for("auth.login"))
                except Exception as e:
                    db.session.rollback()
                    flash("Error al registrar el usuario. Por favor, intenta de nuevo.", "error")

    # Si algo falla o es GET request, mostrar el formulario de registro
    roles = Rol.query.all()
    return render_template("auth/register.html", roles=roles)

@auth_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    session.pop('failed_attempts', None)  # Clear the failed login attempt counter
    flash("Has cerrado sesión con éxito", "success")
    return redirect(url_for("auth.login"))

app/controllers/main_controller.py
from flask import Blueprint, render_template

# Importamos los blueprints de otros módulos
from .admin_controller import admin_blueprint
from .user_controller import user_blueprint
from .auth_controller import auth_blueprint

# Creamos el Blueprint para este controlador principal
main_blueprint = Blueprint('main', __name__, url_prefix="/main")

# Ruta de inicio que muestra las opciones de navegación disponibles
@main_blueprint.route('/')
@main_blueprint.route('/home')
def home():
    return render_template('main.html')

# Función para registrar blueprints a la app principal
def register_blueprints(app):
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(main_blueprint)

app/controllers/user_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from ..models import (
    Usuario,
    Vehiculo,
    HistorialVehiculo,
    Transaccion,
    Novedad,
    Celda,
    Tarifa
)
from .. import db
from flask_login import login_required, current_user
from datetime import datetime
from decimal import Decimal
from flask import send_file, abort
import os
from io import BytesIO
from reportlab.pdfgen import canvas

user_blueprint = Blueprint("user", __name__, url_prefix="/user")


@user_blueprint.route("/gestion", methods=["GET"])
@login_required
def gestion():
    # Obtener vehículos actualmente estacionados (aquellos sin fecha_hora_salida)
    historial_actual = (
        HistorialVehiculo.query.filter(HistorialVehiculo.fecha_hora_salida.is_(None))
        .join(Vehiculo)
        .add_columns(
            Vehiculo.placa,
            Vehiculo.tipo,
            HistorialVehiculo.fecha_hora_entrada,
            HistorialVehiculo.id.label("historial_id")
        )
        .all()
    )

    return render_template(
        "user/gestion.html",
        historial_actual=historial_actual,
    )



@user_blueprint.route("/entrada", methods=["GET", "POST"])
@login_required
def registrar_entrada():
    tipos_vehiculo = ["carro", "moto"]

    if request.method == "POST":
        placa = request.form.get("placa")
        tipo_vehiculo = request.form.get("tipo_vehiculo")

        # Verificar si el vehículo ya está registrado
        vehiculo = Vehiculo.query.filter_by(placa=placa).first()

        # Si el vehículo ya está registrado, verificar si ya existe una entrada sin salida
        if vehiculo:
            entrada_activa = HistorialVehiculo.query.filter_by(
                vehiculo_id=vehiculo.id, fecha_hora_salida=None
            ).first()
            if entrada_activa:
                flash("Este vehículo ya tiene una entrada registrada sin salida.")
                return redirect(url_for("user.gestion"))

        # Si el vehículo no está registrado, crear una nueva instancia y registrarla
        else:
            marca = request.form.get("marca")
            modelo = request.form.get("modelo")
            color = request.form.get("color")
            usuario_id = current_user.id

            nuevo_vehiculo = Vehiculo(
                placa=placa,
                tipo=tipo_vehiculo,
                marca=marca,
                modelo=modelo,
                color=color,
                usuario_id=usuario_id,
            )
            db.session.add(nuevo_vehiculo)
            db.session.commit()
            vehiculo = nuevo_vehiculo
            flash("Vehículo registrado con éxito.")

        # Buscar una celda libre para el tipo de vehículo
        celda_libre = Celda.query.filter_by(
            estado="libre", tipo_vehiculo=tipo_vehiculo
        ).first()
        if celda_libre is None:
            flash("No hay celdas libres para el tipo de vehículo.")
            return redirect(url_for("user.gestion"))

        # Registrar la entrada del vehículo
        nueva_entrada = HistorialVehiculo(
            vehiculo_id=vehiculo.id,
            fecha_hora_entrada=datetime.now(),
            celda_id=celda_libre.id,
        )
        db.session.add(nueva_entrada)

        # Actualizar el estado de la celda a 'ocupada'
        celda_libre.estado = "ocupada"
        db.session.commit()

        flash("Entrada de vehículo registrada con éxito.")
        return redirect(url_for("user.gestion"))

    return render_template("user/entrada.html", tipos_vehiculo=tipos_vehiculo)


@user_blueprint.route("/salida", methods=["GET", "POST"])
@login_required
def registrar_salida():
    if request.method == "POST":
        placa = request.form.get("placa")  # Se obtiene la placa del formulario

        # Buscar el vehículo por la placa para obtener su ID
        vehiculo = Vehiculo.query.filter_by(placa=placa).first()
        if not vehiculo:
            flash("Vehículo no registrado.")
            return redirect(url_for("user.gestion"))
        
        # Buscar el registro de historial más reciente sin fecha de salida
        registro_historial = (
            HistorialVehiculo.query.filter_by(
                vehiculo_id=vehiculo.id, fecha_hora_salida=None
            )
            .order_by(HistorialVehiculo.fecha_hora_entrada.desc())
            .first()
        )

        if registro_historial:
            # Calcula la tarifa provisionalmente (no asignes la salida aún)
            tarifa_id, monto = calcular_tarifa(registro_historial)
            
            # Guarda la información del pago en la sesión para usar en la siguiente página
            session['pago_info'] = {
                'historial_id': registro_historial.id,
                'monto': str(monto),  # Convertir Decimal a string para guardar en la sesión
                'tarifa_id': tarifa_id,
                'vehiculo_id': vehiculo.id,  # Guarda el ID del vehículo para liberar la celda luego
            }

            flash("Salida de vehículo preparada. Proceda con el pago.")
            return redirect(url_for("user.registrar_pago"))
        else:
            flash("No se encontró entrada pendiente de salida para la placa proporcionada.")
            return redirect(url_for("user.gestion"))

    return render_template("user/salida.html")


# Esta función encuentra la tarifa adecuada basada en la duración de la estancia y el tipo de vehículo
def obtener_tarifa(duracion_estancia, tipo_vehiculo):
    # Convertir duracion_estancia a minutos
    minutos_estancia = duracion_estancia.total_seconds() / 60
    # Asegúrate de que minutos_estancia sea un objeto Decimal
    minutos_estancia = Decimal(minutos_estancia)

    # Encuentra la tarifa que esté vigente y corresponda al tipo de vehículo
    tarifa_vigente = Tarifa.query.filter(
        Tarifa.tipo_vehiculo == tipo_vehiculo,
        Tarifa.vigencia_inicio <= datetime.now(),
        Tarifa.vigencia_fin >= datetime.now(),
    ).first()

    if tarifa_vigente:
        # Calcula el monto en base a la duración de la estancia
        monto = minutos_estancia * tarifa_vigente.costo
        return tarifa_vigente.id, round(
            monto, 2)  # Aseguramos que el monto tenga dos decimales

    # En caso de que no exista una tarifa vigente para el tipo de vehículo
    return None, None


# Esta función calcula la tarifa basada en la duración de la estancia del vehículo
def calcular_tarifa(historial_vehiculo):
    # Usa la hora actual como hora de salida provisional para el cálculo de la tarifa
    fecha_hora_salida_provisional = datetime.now()
    duracion_estancia = fecha_hora_salida_provisional - historial_vehiculo.fecha_hora_entrada
    
    tipo_vehiculo = historial_vehiculo.vehiculo.tipo
    tarifa_id, monto = obtener_tarifa(duracion_estancia, tipo_vehiculo)
    return tarifa_id, monto



@user_blueprint.route("/pago", methods=["GET", "POST"])
@login_required
def registrar_pago():
    if 'pago_info' not in session:
        flash("Información de pago no encontrada.")
        return redirect(url_for("user.gestion"))

    pago_info = session['pago_info']
    
    if request.method == "POST":
        metodo_pago = request.form.get("metodo_pago")

        historial_vehiculo = HistorialVehiculo.query.get(pago_info['historial_id'])
        if not historial_vehiculo or historial_vehiculo.fecha_hora_salida is not None:
            flash("No se encontró el historial del vehículo o ya se registró la salida.")
            return redirect(url_for("user.gestion"))
        
        # Si aún no se ha registrado la salida, hazlo ahora
        if historial_vehiculo.fecha_hora_salida is None:
            historial_vehiculo.fecha_hora_salida = datetime.now()

        # Crear la transacción con la tarifa correspondiente
        nueva_transaccion = Transaccion(
            historial_vehiculo_id=historial_vehiculo.id,
            tarifa_id=pago_info['tarifa_id'],
            fecha_hora_pago=datetime.now(),
            monto=Decimal(pago_info['monto']),
            metodo_pago=metodo_pago,
        )

        # Añadir la nueva transacción y guardar los cambios en la base de datos
        db.session.add(nueva_transaccion)
        db.session.commit()

        # Liberar la celda ocupada por el vehículo
        celda_ocupada = Celda.query.get(historial_vehiculo.celda_id)
        celda_ocupada.estado = "libre"

        # Limpia la información de pago de la sesión
        session.pop('pago_info', None)

        flash("Pago registrado con éxito.")

        # Redirige al ticket después de registrar el pago con éxito
        return redirect(url_for('user.generar_ticket', transaccion_id=nueva_transaccion.id))

    # Mostrar el formulario de pago con la información de la sesión si aún no se ha realizado el POST
    return render_template("user/pagos.html", 
                           monto=pago_info['monto'], 
                           metodo_pago=["efectivo", "transferencia", "tarjeta"], 
                           historial_id=pago_info['historial_id'])



@user_blueprint.route("/novedad", methods=["GET", "POST"])
@login_required
def reportar_novedad():
    if request.method == "POST":
        placa = request.form.get("placa")
        descripcion = request.form.get("descripcion")

        # Buscar el vehículo por placa para obtener su id
        vehiculo = Vehiculo.query.filter_by(placa=placa).first()
        if not vehiculo:
            flash("No se encontró un vehículo con la placa proporcionada.")
            return redirect(url_for("user.novedad"))

        # Crear la novedad
        nueva_novedad = Novedad(
            descripcion=descripcion,
            vehiculo_id=vehiculo.id,
            fecha_hora=datetime.now(),
            reportado_por=current_user.id,  # Usar el nombre de campo correcto aquí
        )

        # Añadir la novedad y guardar los cambios en la base de datos
        db.session.add(nueva_novedad)
        db.session.commit()

        flash("Novedad reportada con éxito.")

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
    <title>AutosColombia</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    <!-- Barra de Navegación -->
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">AutosColombia</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="offcanvas"
          data-bs-target="#offcanvasNavbar"
          aria-controls="offcanvasNavbar"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="offcanvas offcanvas-end"
          tabindex="-1"
          id="offcanvasNavbar"
          aria-labelledby="offcanvasNavbarLabel"
        >
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
              AutosColombia
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="offcanvas"
              aria-label="Close"
            ></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Gestion
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('user.gestion') }}">Existencia</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('user.registrar_entrada') }}">Ingreso</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('user.registrar_salida') }}">Salida</a></li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li>
                    <a class="dropdown-item" href="{{ url_for('user.registrar_pago') }}">Pagos</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('user.reportar_novedad') }}"
                  >Novedades</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('user.historial_pagos') }}"
                  >Reportes</a
                >
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Configuración
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('admin.tarifa') }}">Tarifas</a></li>
                  <li>
                    <hr class="dropdown-divider" />
                  </li>
                  <li>
                    <a class="dropdown-item" href="{{ url_for('admin.editar_user') }}">Editar Usuario</a>
                    <a class="dropdown-item" href="{{ url_for('admin.cambiar_password') }}">Cambiar Contraseña</a>
                    <a class="dropdown-item" href="{{ url_for('admin.permiso_users') }}">Editar Permisos</a>
                  </li>
                </ul>              
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Cerrar</a>
              </li>
            </ul>
            <form class="d-flex mt-3" role="search">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-outline-success" type="submit">
                Search
              </button>
            </form>
          </div>
        </div>
      </div>
    </nav>

    <!-- Contenido Principal -->
    <main role="main" class="container mt-4">
      {% block content %}{% endblock %}
    </main>

    <!-- Pie de Página -->
    <footer class="footer mt-auto py-3 bg-light">
      <div class="container text-center">
        <span class="text-muted"
          >&copy; 2023 AutosColombia. Todos los derechos reservados.</span
        >
      </div>
    </footer>

    {% block scripts %}{% endblock %}
  </body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Inicio - Sistema de Parqueadero</title>
        <!-- Bootstrap CSS -->
<link rel="stylesheet" href="/static/css/bootstrap/bootstrap.min.css">

<link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <header>
        <h1>Bienvenido al Sistema de Gestión de Parqueaderos</h1>
        <!-- Aquí puedes añadir una barra de navegación o enlaces de login/logout si es necesario -->
    </header>

    <main>
        <!-- Contenido principal de la página -->
        <div>
            <h2>Navegación</h2>
            <nav>
                <ul>
                    <!-- Se supone que aquí se verificará si el usuario es un administrador o un usuario común para mostrar enlaces adecuados -->
                    <li><a href="{{ url_for('admin.configuracion') }}">Configuración (Admin)</a></li>
                    <li><a href="{{ url_for('admin.reportes') }}">Reportes (Admin)</a></li>
                    <li><a href="{{ url_for('user.gestion') }}">Gestión (Usuario)</a></li>

                </ul>
            </nav>
        </div>
    </main>

    <footer>
        <p>&copy; 2023 Sistema de Gestión de Parqueaderos</p>
    </footer>
</body>
</html>

app/templates/main.html
{% extends "base.html" %}

{% block head %}
  {{ super() }}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1>Bienvenido al Sistema de Gestión de Parqueaderos</h1>

    <!-- Mensajes flash para notificaciones -->
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="alert alert-success" role="alert">{{ messages[0] }}</div>
      {% endif %}
    {% endwith %}

    <div>
      <h2>Navegación</h2>
      <nav>
        <ul>
          <!-- Carrusel de imágenes (reemplaza '...' con las rutas de tus imágenes) -->
          <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ url_for('static', filename='images/1.jpg') }}" class="d-block w-100" alt="Imagen 1">
              </div>
              <div class="carousel-item">
                <img src="{{ url_for('static', filename='images//2.jpg') }}" class="d-block w-100" alt="Imagen 2">
              </div>
              <div class="carousel-item">
                <img src="{{ url_for('static', filename='images//3.jpg') }}" class="d-block w-100" alt="Imagen 3">
              </div>
            </div>
          </div>

          <!-- Asegúrate de que estos endpoints estén definidos en tus rutas de Flask -->
          <li><a href="{{ url_for('admin.reportes') }}">Reportes (Admin)</a></li>
          <li><a href="{{ url_for('user.gestion') }}">Gestión (Usuario)</a></li>
        </ul>
      </nav>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ super() }}
{% endblock %}